<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>checkbox ship to diff addr</name>
   <tag></tag>
   <elementGuidId>b28a9393-7840-4eff-86d0-b162be222aef</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#ship-to-different-address-checkbox</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='ship-to-different-address-checkbox']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;Ship to a different address?&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>2e9b72f7-1fc3-432b-9b23-8e391288d71c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ship-to-different-address-checkbox</value>
      <webElementGuid>487a3ae5-a0b1-4392-bd68-7a010f90ba9b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>woocommerce-form__input woocommerce-form__input-checkbox input-checkbox</value>
      <webElementGuid>5b45783c-ac5a-412b-a640-a9e19a0e74b8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>07db3d48-26b6-442a-a10f-884b2335ffe9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>ship_to_different_address</value>
      <webElementGuid>237e8f86-933f-4628-81eb-fb173ce5ca02</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>13ed8273-fe79-4e14-8424-a9bf930ccde5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ship-to-different-address-checkbox&quot;)</value>
      <webElementGuid>59a39359-15b8-4c76-a80c-4669c3d5d855</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='ship-to-different-address-checkbox']</value>
      <webElementGuid>156a514d-69fe-46ed-83b6-401399a6985d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//h3[@id='ship-to-different-address']/label/input</value>
      <webElementGuid>7a89fcc2-7d53-46c9-879d-8971dad1fb03</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//label/input</value>
      <webElementGuid>14e29086-239a-478e-b3f7-a4a74f07f09f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'ship-to-different-address-checkbox' and @type = 'checkbox' and @name = 'ship_to_different_address']</value>
      <webElementGuid>2603d202-048a-413c-abb5-e9d9ad642e8f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
