<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>search icon</name>
   <tag></tag>
   <elementGuidId>40b74738-64ef-4467-9919-98810d6c3ac8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>i.ellie-icon-search</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//section[@id='search-2']/form/button/i</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=button[name=&quot;Search &quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>i</value>
      <webElementGuid>4936c35c-b2cf-4862-bba7-e617b0e8f710</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ellie-icon-search</value>
      <webElementGuid>86747cc4-02c6-4519-b7fb-6db10eb861ca</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;search-2&quot;)/form[@class=&quot;search-form&quot;]/button[@class=&quot;search-submit&quot;]/i[@class=&quot;ellie-icon-search&quot;]</value>
      <webElementGuid>47d80442-6b74-4e72-a2bb-efed15963fc6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//section[@id='search-2']/form/button/i</value>
      <webElementGuid>0dc64739-b5a6-4dd1-a47f-271c6af56aaa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button/i</value>
      <webElementGuid>b023b2ca-4afb-47ef-b4b0-14110c333c4a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
