<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>first result thumbnail</name>
   <tag></tag>
   <elementGuidId>8d0f81a5-3e7d-4fd7-9395-95ab98dc8bf7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#post-54 > a.post-thumbnail</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//article[@id='post-54']/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#post-54 a >> nth=1</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>6c4859d1-6bd6-4bbd-a278-d6618154d9a1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>post-thumbnail</value>
      <webElementGuid>bcffb27d-72ef-4d22-83af-c0120daa5f52</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://cms.demo.katalon.com/product/flying-ninja/</value>
      <webElementGuid>07c9b61c-c426-4245-a34a-7e680810a176</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-hidden</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>53c65a5f-8bf1-48d7-9ff7-368af4ec3cc9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;post-54&quot;)/a[@class=&quot;post-thumbnail&quot;]</value>
      <webElementGuid>840daf3e-0ca8-40e3-9e0a-e5673bc4bf09</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//article[@id='post-54']/a</value>
      <webElementGuid>4b47a90a-8839-4ee0-945e-2bcc5afa466d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Flying Ninja'])[1]/following::a[1]</value>
      <webElementGuid>0f2c4b12-3fe6-4137-96e5-0ce02f06967a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='on Patient Ninja'])[1]/following::a[2]</value>
      <webElementGuid>cc5e3edf-cac5-49a7-8380-fafb4dc4946e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='on Flying Ninja'])[1]/preceding::a[1]</value>
      <webElementGuid>dda7a788-f580-48b0-a13b-373815cfd0c0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, 'https://cms.demo.katalon.com/product/flying-ninja/')])[2]</value>
      <webElementGuid>acd114dd-dd89-4634-a290-48b30128fd8c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//article[2]/a</value>
      <webElementGuid>eaf4979a-7f8b-4531-aa27-e6be6d7d4f87</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'https://cms.demo.katalon.com/product/flying-ninja/']</value>
      <webElementGuid>22c3a185-857a-43f6-bb3d-0851de3654d2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
